#!/usr/bin/env bash

rm -rf *.zip
mkdir -p movit/icons
cp -R js movit/
cp icons/*.png movit/icons/
cp LICENSE movit/
cp manifest.json movit/
cp popup.html movit/
cd movit
zip -r -FS ../movit.zip * --exclude *.git*
cd -
rm -rf movit
